

#server port number
server:
  port: 2210

#View Resolver  
#Spring connection pooling
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: Kunal2209
  
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
 
  main:
       banner-mode: off
  mail:
       protocol: smtp
       host: smtp.mailtrap.io
       port:  2525 
       username: f2f1c48419d832      
       password: 9527240dddac9f
       properties.mail.smtp:
                 auth: true
                 starttls.enable: true 
        



